#!/usr/bin/env ruby

require_relative 'japanese'

adjectives = Japanese.adjectives
adjectives.shuffle!

n = 10
generator = Random.new

adjectives.take(n).each do |adjective|
  is_present = [true, false].sample
  is_positive = [true, false].sample
  is_long = [true, false].sample

  if is_present && is_positive
    verb = 'is'
  elsif is_present && !is_positive
    verb = 'isn\'t'
  elsif !is_present && is_positive
    verb = 'was'
  else
    verb = 'wasn\'t'
  end
  print "#{is_long ? 'Long' : 'Short'}: It #{verb} #{adjective.definition}. -> "

  guess = gets.chomp

  answer = adjective.is(is_present, is_positive, is_long)

  if guess == answer
    puts "Right!"
  else
    puts "Wrong. Expected: #{answer}"
    puts "                 #{guess}"
  end
  puts
end
