#!/usr/bin/env ruby

require_relative 'japanese'

adjectives = Japanese.adjectives
adjective = adjectives.find { |adjective| adjective.hiragana == ARGV[0] }

puts "is_i? #{adjective.is_i?}"
puts "is_na? #{adjective.is_na?}"
puts
puts "PRESENT"
puts adjective.is(true, true, false)
puts adjective.is(true, true, true)
puts adjective.is(true, false, false)
puts adjective.is(true, false, true)
puts
puts "PAST"
puts adjective.is(false, true, false)
puts adjective.is(false, true, true)
puts adjective.is(false, false, false)
puts adjective.is(false, false, true)
