#!/usr/bin/env ruby

require_relative 'japanese'

nouns = Japanese.nouns
nouns.shuffle!
adjectives = Japanese.adjectives
adjectives.shuffle!
verbs = Japanese.verbs
verbs.shuffle!

n = 3
generator = Random.new

n.times do
  type = generator.rand(3)
  if type == 0
    word = nouns.pop
    is_positive = [true, false].sample
    if is_positive
      answer = "#{word.kana}でしょう"
    else
      answer = "#{word.kana}じゃないでしょう"
    end
    blurb = "is probably #{word.definition} [noun]"
  elsif type == 1
    word = adjectives.pop
    is_positive = [true, false].sample
    answer = "#{word.long(true, is_positive)}でしょう"
    blurb = "#{word.definition} [adjective]"
  else
    word = verbs.pop
    is_present = true
    is_positive = [true, false].sample
    is_want = [true, false].sample

    if is_want
      mode = 'want'
      answer = "#{word.want(is_present, is_positive).short(is_present, is_positive)}んでしょう"
    else
      is_short = [true, false].sample
      if is_short
        mode = 'short'
        answer = "#{word.short(is_present, is_positive)}んです"
      else
        mode = 'long'
        answer = "#{word.long(is_present, is_positive)}んです"
      end
    end

    blurb = "%s [verb, %s, %s, %s]" % [word.definition, is_present ? 'present' : 'past', is_positive ? 'positive' : 'negative', mode]
  end

  print "Explain #{blurb} (#{word.kana}) -> "
  guess = gets.chomp

  if guess == answer
    puts "Right!"
  else
    puts "Wrong. It's #{answer}."
  end
  puts
end
