#!/usr/bin/env ruby

require_relative 'japanese'

Japanese.expressions.shuffle.each do |expression|
  print "#{expression.definition}? "
  answer = gets.chomp
  if answer == expression.hiragana
    puts "Right!"
  else
    puts "Wrong..."
    puts "  Expected: #{expression.hiragana}"
    puts "    Actual: #{answer}"
  end
  puts
end
