#!/usr/bin/env ruby

require 'json'
require 'optparse'
require 'set'

kanjis = JSON.parse(File.read('kanji.json'))
kanjis.each do |kanji|
  kanji['tags'] = Set.new(kanji['tags'])
end

options = {n: nil, tags: Set.new}
OptionParser.new do |opts|
  opts.banner = "Usage: kanji [-n #] [--tags a,b,c]"
  opts.on('-n', '--n NUMBER', OptionParser::DecimalInteger, 'Number of kanji') do |v|
    options[:n] = v
  end
  opts.on('-t', '--tags TAGS', String, 'Tags') do |v|
    options[:tags].merge(v.split(/,/))
  end
end.parse!

kanjis = kanjis.select { |kanji| kanji['tags'].intersect?(options[:tags]) }

if options[:n].nil?
  options[:n] = kanjis.size
end
  
kanjis = kanjis.shuffle.take(options[:n])

kanjis.each do |kanji|
  print "#{kanji['definition']}をかいてください。"
  gets
  puts "#{kanji['kanji']}"
  puts
end
