#!/usr/bin/env ruby

require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

n = 10

verbs.take(n).each do |verb|
  isAbbreviated = [true, false].sample
  if isAbbreviated
    k = "きゃ"
  else
    k = "ければ"
  end

  print "to have #{verb.definition} (#{verb.kana}, #{isAbbreviated ? 'abbreviated' : 'not abbreviated'}) -> ".green
  guess = gets.chomp

  answer = "#{verb.short(true, false).chop}#{k}いけません"

  if guess == answer
    puts "Right!"
  else
    puts "Wrong."
    puts "  Expected: #{answer}"
    puts "    Actual: #{guess}"
  end
  puts
end
