#!/usr/bin/env ruby

require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

verbs.take(2).each do |verb|
  print "#{verb.phonetic}? "
  answer = gets.chomp
  if (answer == 'u' && verb.is_u?) || (answer == 'ru' && verb.is_ru?)
    puts "Right!"
  else
    puts "Wrong..."
  end
  puts
end
