#!/usr/bin/env ruby

require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

n = 10
generator = Random.new

verbs.take(n).each do |verb|
  print "#{verb.kana} (#{verb.definition})? "
  guess = gets.chomp
  answer = verb.potential.kana
  if guess == answer
    puts "Right!"
  else
    puts "Wrong. It's #{answer}."
  end
  puts
end
