#!/usr/bin/env ruby

require 'optparse'
require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

options = {n: 10, full: false}
OptionParser.new do |opts|
  opts.banner = "Usage: verb_short [-n #] [-b before] [-a after] [category...]"
  opts.on('-n', '--n NUMBER', OptionParser::DecimalInteger, 'Number of questions') do |v|
    options[:n] = v
  end
  opts.on('-f', '--full', 'Conjugate all tenses') do |v|
    options[:full] = true
  end
end.parse!

generator = Random.new

verbs.take(options[:n]).each do |verb|
  if options[:full]
    times = [true, false]
    positives = [true, false]
  else
    times = [[true, false].sample]
    positives = [[true, false].sample]
  end

  times.each do |is_present|
    positives.each do |is_positive|
      prompt = "#{verb.kana} (#{verb.definition})"
      if is_positive
        print "#{prompt} #{is_present ? 'PRESENT' : 'PAST'} POSITIVE ".green
      else
        print "#{prompt} #{is_present ? 'PRESENT' : 'PAST'} NEGATIVE ".red
      end
      guess = gets.chomp

      answer = verb.short(is_positive, is_present)

      if guess == answer
        puts "Right!"
      else
        puts "Wrong. It's #{answer}."
      end
      puts
    end
  end
end
