#!/usr/bin/env ruby

require 'json'
require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

n = 10

verbs.take(n).each do |verb|
  print "#{verb.definition}? "
  answer = gets.chomp
  if answer == verb.hiragana
    puts "Right!"
  else
    puts "Wrong..."
  end
  puts
end
