#!/usr/bin/env ruby

require_relative 'japanese'

verbs = Japanese.verbs
verbs.shuffle!

n = 10
generator = Random.new

movers = [
  verbs.find { |verb| verb.phonetic == 'いく' },
  verbs.find { |verb| verb.phonetic == 'くる' },
  verbs.find { |verb| verb.phonetic == 'かえる' }
]

verbs.take(n).each do |verb|
  mover = movers.sample
  print "#{mover.definition} #{verb.definition} (#{verb.phonetic}) -> "
  guess = gets.chomp

  answer = verb.stem + 'に' + mover.long

  if guess == answer
    puts "Right!"
  else
    puts "Wrong. It's #{answer}."
  end
  puts
end
